(in-package :mnas-ansys/cfx/pre)

(require :nodgui)


(defun Feet-to-Metres ()
  (nodgui:with-nodgui ()
    (nodgui:wm-title nodgui:*tk* "Feet to Metres")                           
    (let ((content (make-instance 'nodgui:frame)))                    
      (nodgui:configure content :padding "3 3 12 12")                
      (nodgui:grid content 0 0 :sticky "nsew")
      (nodgui:grid-columnconfigure nodgui:*tk* 0 :weight 1)
      (nodgui:grid-rowconfigure nodgui:*tk* 0 :weight 1)

      (let* ((feet-entry (make-instance   'nodgui:entry   :master content :width 7))    
             (metres-label (make-instance 'nodgui:label :master content :text ""))
             (label-feet (make-instance   'nodgui:label   :master content :text "feet"))
             (label-eq-to (make-instance  'nodgui:label  :master content :text "is equivalent to"))
             (label-metres (make-instance 'nodgui:label :master content :text "metres")))
        (flet ((calculate ()                                                 
                 (let ((feet (read-from-string (nodgui:text feet-entry))))
                   (setf (nodgui:text metres-label)
                         (if (numberp feet)
                             (/ (round (* 0.3048 feet 10000.0)) 10000.0)
                             "")))))
          
          (nodgui:grid feet-entry   1 2 :sticky "we" :padx 5 :pady 5)                 
          (nodgui:grid label-feet   1 3 :sticky "w"  :padx 5 :pady 5)
          (nodgui:grid label-eq-to  2 1 :sticky "e"  :padx 5 :pady 5)
          (nodgui:grid metres-label 2 2 :sticky "we" :padx 5 :pady 5)
          (nodgui:grid label-metres 2 3 :sticky "w"  :padx 5 :pady 5)
          (nodgui:grid (make-instance  'nodgui:button :master content :text "Calculate" :command #'calculate)
                       3 3 :sticky "w"  :padx 5 :pady 5)
          (nodgui:focus feet-entry)                                                 
          (nodgui:bind nodgui:*tk* "<Return>" (lambda (evt) (calculate))))))
    ))
