#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: README
#+DATE: <2020-12-17 Чт>
#+AUTHOR:
#+EMAIL: mnasoft@gmail.com
#+LANGUAGE: ru
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)

# mnas-icem
* Назначение

Предназначен для выполнения операций с представлением tin-файлов 
(представления геометрии) системы ANSYS ICEM

* Получение tin-файлов из расчетного кластера

#+BEGIN_SRC bash
# Запускать из оболочки bash.
cd /home/namatv/quicklisp/local-projects/ANSYS/mnas-icem/tin;
rsync.exe -Pavzhe ssh namatv@hp1:/_gas/CFX/otd11/namatv/a32_base/PR-01/GT/*.tin .
rsync.exe -Pavzhe ssh namatv@hp1:/_gas/CFX/otd11/namatv/a32_base/PR-01/GU/*.tin .
#+END_SRC

#+RESULTS:

* [/] ToDo
- [ ] Добавить каждого класса функцию tag, которая будет возвращать.
* Схема именования геометрии

| P04         |      |         |     |
| P04_E_C     | Edge | Curve   |     |
| P04_H_C_BIG | Hole | Curve   | Big |
| P04_H_S     | Hole | Surface |     |

ASM.05/P05 ASM.05/P05_E_C ASM.05/P05_H_S ASM.05/P05_H_C_BIG
ASM.06/P06 ASM.06/P06_E_C ASM.06/P06_H_S ASM.06/P06_H_C_BIG
ASM.07/P07 ASM.07/P07_E_C ASM.07/P07_H_S ASM.07/P07_H_C_BIG
ASM.08/P08 ASM.08/P08_E_C ASM.08/P08_H_S ASM.08/P08_H_C_BIG
ASM.09/P09 ASM.09/P09_E_C ASM.09/P09_H_S ASM.09/P09_H_C_BIG
ASM.10/P10 ASM.10/P10_E_C ASM.10/P10_H_S ASM.10/P10_H_C_BIG

ASM.11/P11 ASM.11/P11_E_C ASM.11/P11_H_S ASM.11/P11_H_C

ASM.12-1/P12-1 ASM.12-1/P12-1_E_C ASM.12-1/P12-1_H_S ASM.12-1/P12-1_H_C

ASM.12-2/P12-2 ASM.12-2/P12-2_E_C ASM.12-2/P12-2_H_S ASM.12-2/P12-2_H_C

* Информация по обучению
** Построение призматического подслоя для жидкостей (газов) fluid
   - для определения высоты призматического слоя необходимо
     пользоваться критерием Y+;
   - для определения критерия Y+ можно воспользоваться сайтом
     [[cfd-online.com]] : Home->Tools->Y+ Estimation;
   - рекомендованый коэффициент роста толщины при переходе от слоя к
     слою должен быть не более 1.3;
   - высота последней призматической ячейки должна быть близка к
     размеру ячеек прилегающей к ней сетки;
   - длина (ширина) последней призматической ячейки должна быть близка
     к ее высоте (толщине последнего слоя);
   - рекомендованное количество слоев для призматической сетки не
     более 12, с учетом опыта проведения расчетов от 3 до 5;
** Особенности построения сетки для твердотельных доменов
   - количество ячеек по толщине для решения совмещеной задачи
     теплопроводности следует выбирать не менее 3;
   - тип сетки лучше выбирать гексагональную.
** Рекомендации по размеру ячеек в отверстиях
   - на диаметре должно располагаться пять ячеек.
** Рекомендации по типу сетки
   - для потоков, имеющих в своей структуре крупномасштабные вихри
     необходимо использовать тетраэдрическую сетку;
** Верификация
   - для верификации результатов численного моделирования
     рекомендуется использовать ресурс [[rutracker.org]] и ключевые слова:
     ANSYS Validition.
   
    
    
    
  
